// <auto-generated />
using System;
using GroupInvest.Microservices.Auditoria.Infra.DataAccess.Contextos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GroupInvest.Microservices.Auditoria.Infra.DataAccess.Migrations
{
    [DbContext(typeof(MicroserviceAuditoriaDbContext))]
    partial class MicroserviceAuditoriaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GroupInvest.Microservices.Auditoria.Domain.Entidades.AuditoriaBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Agregado")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("AgregadoId")
                        .HasColumnType("int");

                    b.Property<string>("Conteudo")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Operacao")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Auditorias");
                });
#pragma warning restore 612, 618
        }
    }
}
