//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupInvest.Microservices.Participantes.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensagens {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagens() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GroupInvest.Microservices.Participantes.Domain.Resources.Mensagens", typeof(Mensagens).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Essa adesão já foi realizada anteriormente..
        /// </summary>
        internal static string AdesaoExistente {
            get {
                return ResourceManager.GetString("AdesaoExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adesão não foi encontrada..
        /// </summary>
        internal static string AdesaoNaoEncontrada {
            get {
                return ResourceManager.GetString("AdesaoNaoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A adesão deve possuir ao menos uma cota..
        /// </summary>
        internal static string AdesaoNumeroMinimoCotas {
            get {
                return ResourceManager.GetString("AdesaoNumeroMinimoCotas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O participante deve ser informado na adesão..
        /// </summary>
        internal static string AdesaoSemParticipante {
            get {
                return ResourceManager.GetString("AdesaoSemParticipante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O período deve ser informado na adesão..
        /// </summary>
        internal static string AdesaoSemPeriodo {
            get {
                return ResourceManager.GetString("AdesaoSemPeriodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O commit não efetuou alterações na base de dados..
        /// </summary>
        internal static string CommitError {
            get {
                return ResourceManager.GetString("CommitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O participante possui adesão ativa..
        /// </summary>
        internal static string ParticipanteComAdesaoAtiva {
            get {
                return ResourceManager.GetString("ParticipanteComAdesaoAtiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O email informado para o participante já está sendo utilizado..
        /// </summary>
        internal static string ParticipanteEmailExistente {
            get {
                return ResourceManager.GetString("ParticipanteEmailExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do participante deve possuir pelo menos três caracteres..
        /// </summary>
        internal static string ParticipanteNomeMinimoCaracteres {
            get {
                return ResourceManager.GetString("ParticipanteNomeMinimoCaracteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do participante deve ser informado..
        /// </summary>
        internal static string ParticipanteNomeNulo {
            get {
                return ResourceManager.GetString("ParticipanteNomeNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O participante deve ser informado..
        /// </summary>
        internal static string ParticipanteNulo {
            get {
                return ResourceManager.GetString("ParticipanteNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O participante deve estar ativo..
        /// </summary>
        internal static string ParticipanteStatusAtivo {
            get {
                return ResourceManager.GetString("ParticipanteStatusAtivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número de telefone do participante deve possuir pelo menos 9 caracteres..
        /// </summary>
        internal static string ParticipanteTelefoneMinimoCaracteres {
            get {
                return ResourceManager.GetString("ParticipanteTelefoneMinimoCaracteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ano de referência informado para o perído já foi cadastrado..
        /// </summary>
        internal static string PeriodoAnoReferenciaExistente {
            get {
                return ResourceManager.GetString("PeriodoAnoReferenciaExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ano de referência deve ser a partir de 2020..
        /// </summary>
        internal static string PeriodoAnoReferenciaInvalido {
            get {
                return ResourceManager.GetString("PeriodoAnoReferenciaInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de início do período deve ser informada..
        /// </summary>
        internal static string PeriodoDataInicioNula {
            get {
                return ResourceManager.GetString("PeriodoDataInicioNula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de término do período deve ser informada..
        /// </summary>
        internal static string PeriodoDataTerminoNula {
            get {
                return ResourceManager.GetString("PeriodoDataTerminoNula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O período possui adesões ativas..
        /// </summary>
        internal static string PeriodoPossuiAdesoesAtivas {
            get {
                return ResourceManager.GetString("PeriodoPossuiAdesoesAtivas", resourceCulture);
            }
        }
    }
}
