// <auto-generated />
using System;
using GroupInvest.Microservices.Mensalidades.Infra.DataAccess.Contextos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GroupInvest.Microservices.Mensalidades.Infra.DataAccess.Migrations
{
    [DbContext(typeof(MicroserviceMensalidadesDbContext))]
    [Migration("20200826060735_add-column-periodo-mensalidade")]
    partial class addcolumnperiodomensalidade
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GroupInvest.Microservices.Mensalidades.Domain.Entidades.Mensalidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataReferencia")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataVencimento")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ParticipanteId")
                        .HasColumnType("int");

                    b.Property<int?>("PeriodoId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorDevido")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("ValorPago")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("ParticipanteId");

                    b.HasIndex("PeriodoId");

                    b.ToTable("Mensalidades");
                });

            modelBuilder.Entity("GroupInvest.Microservices.Mensalidades.Domain.Entidades.Participante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Participantes");
                });

            modelBuilder.Entity("GroupInvest.Microservices.Mensalidades.Domain.Entidades.Periodo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AnoReferencia")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataInicioPeriodo")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataTerminoPeriodo")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Periodos");
                });

            modelBuilder.Entity("GroupInvest.Microservices.Mensalidades.Domain.Entidades.Mensalidade", b =>
                {
                    b.HasOne("GroupInvest.Microservices.Mensalidades.Domain.Entidades.Participante", "Participante")
                        .WithMany()
                        .HasForeignKey("ParticipanteId");

                    b.HasOne("GroupInvest.Microservices.Mensalidades.Domain.Entidades.Periodo", "Periodo")
                        .WithMany()
                        .HasForeignKey("PeriodoId");
                });
#pragma warning restore 612, 618
        }
    }
}
